name: My-GitHubActions-Basics
on: 
  push: 
    branches: 
      - main

jobs: 
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print nice message
        run: echo "Hello World"

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Print secret
        run: echo "AWS_KEY=${{ secrets.AWS_KEY }}"
        
        
        
